name: breeds
description: "Project for technical test for PRAGMA"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  intl: ^0.18.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  oktoast: ^3.4.0
  percent_indicator: ^4.2.3
  mocktail: ^1.0.2
  bloc_test: ^9.1.5
  fullscreen_image_viewer: ^0.0.6
  dart_ipify: ^1.1.1
  meta: ^1.10.0
  gap: ^3.0.1
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  dartz: ^0.10.1
  package_info_plus: ^5.0.1
  patrol: ^3.6.0
  flutter_launcher_icons: ^0.13.1
  # l10n_breeds:
  #   git:
  #     url: https://github.com/wilver06w/l10n_breeds.git
  #     ref: main
  # breeds_widget:
  #   git:
  #     url: https://github.com/wilver06w/breeds_widget.git
  #     ref: main
  # utils_breeds:
  #   git:
  #     url: https://github.com/wilver06w/utils_breeds.git
  #     ref: main
  # models_breeds:
  #   git:
  #     url: https://github.com/wilver06w/models_breeds.git
  #     ref: main
  # network_breeds:
  #   git:
  #     url: https://github.com/wilver06w/network_breeds.git
  #     ref: main
  l10n_breeds:
    path: ../l10n_breeds
  breeds_widget:
    path: ../breeds_widget
  utils_breeds:
    path: ../utils_breeds
  models_breeds:
    path: ../models_breeds
  network_breeds:
    path: ../network_breeds
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
    android: 'launcher_icon'
    image_path: 'assets/image/icon.jpg'
    ios: true
    min_sdk_android: 21
flutter:
  uses-material-design: true
  assets:
  - config/
  - assets/animations/loading/
  - assets/image/
  - assets/svg/